export interface TriageQuestion {
  id: string;
  text: string;
  type: 'boolean';
  expectedAnswer: boolean;
  failureMessage: string;
  isBlocking: boolean;
}

export const TRIAGE_QUESTIONS: TriageQuestion[] = [
  { id: '1', text: '1. Você está se sentindo bem hoje?', type: 'boolean', expectedAnswer: true, failureMessage: 'Doador não se sente bem.', isBlocking: true },
  { id: '2', text: '2. Já doou Sangue alguma vez? Quantas vezes? Quando foi a última doação?', type: 'boolean', expectedAnswer: true, failureMessage: 'Primeira doação (Apenas informativo).', isBlocking: false },
  { id: '3', text: '3. Teve problema em doação anterior? Sentiu mal estar, tontura, desmaio?', type: 'boolean', expectedAnswer: false, failureMessage: 'Relatou reação em doação anterior.', isBlocking: false },
  { id: '4', text: '4. Alguma vez foi recusado como doador de sangue? Qual o motivo?', type: 'boolean', expectedAnswer: false, failureMessage: 'Já foi recusado anteriormente.', isBlocking: false },
  { id: '5', text: '5. Foi chamado para repetir os exames do banco de sangue alguma vez?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico de convocação para exames.', isBlocking: false },
  { id: '6', text: '6. Qual o motivo da sua doação? Obter exames?', type: 'boolean', expectedAnswer: false, failureMessage: 'Doação com intuito de exames.', isBlocking: true },
  { id: '7', text: '7. Dormiu bem esta noite? Quantas horas? (minimo de 06 horas)', type: 'boolean', expectedAnswer: true, failureMessage: 'Não cumpriu o repouso mínimo.', isBlocking: true },
  { id: '8', text: '8. Está em jejum? Quando foi a sua última doação?', type: 'boolean', expectedAnswer: false, failureMessage: 'Doador em jejum prolongado.', isBlocking: true },
  { id: '9', text: '9. Faz uso diário de bebidas alcoólicas? Fez uso nas últimas 12 hs?', type: 'boolean', expectedAnswer: false, failureMessage: 'Ingestão de álcool recente.', isBlocking: true },
  { id: '10', text: '10. Vai trabalhar e/ou dirigir após a doação? Qual tipo de veículo?', type: 'boolean', expectedAnswer: false, failureMessage: 'Atividade de risco pós-doação.', isBlocking: true },
  { id: '11', text: '11. Faz uso regular de alguma medicação? Qual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Uso regular de medicação.', isBlocking: false },
  { id: '12', text: '12. Fez uso de alguma medicação nos últimos 07 dias?', type: 'boolean', expectedAnswer: false, failureMessage: 'Uso recente de medicação.', isBlocking: false },
  { id: '13', text: '13. Fez uso de alguma vacina nos últimos 30 dias? Qual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Vacinação recente.', isBlocking: false },
  { id: '14', text: '14. Fez uso de vacina derivada de sangue no último ano? (Hepatite, Rhogan, S. Hiperimunes)', type: 'boolean', expectedAnswer: false, failureMessage: 'Uso de imunoglobulina/soro.', isBlocking: true },
  { id: '15', text: '15. Foi mordido por algum animal? Fez uso de vacina contra raiva neste último ano?', type: 'boolean', expectedAnswer: false, failureMessage: 'Risco de raiva.', isBlocking: true },
  { id: '16', text: '16. Tem antecedentes de Doença de Chagas? (doença, sorologia +, familiar)', type: 'boolean', expectedAnswer: false, failureMessage: 'Antecedente de Chagas.', isBlocking: true },
  { id: '17', text: '17. Tem antecedentes de Hepatite? (doença, ictericia, sorologia +, contato famílias < 06 meses)', type: 'boolean', expectedAnswer: false, failureMessage: 'Antecedente de Hepatite.', isBlocking: true },
  { id: '18', text: '18. Já teve malária ou esteve em área endêmica nos últimos 12 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico ou área de Malária.', isBlocking: true },
  { id: '19', text: '19. Viajou ou morou fora da Brasil? Morou na Europa?', type: 'boolean', expectedAnswer: false, failureMessage: 'Viagem internacional.', isBlocking: false },
  { id: '20', text: '20. No último ano teve Toxoplasmose, Mononucleose, Leptospirose, Herpes?', type: 'boolean', expectedAnswer: false, failureMessage: 'Infecção recente.', isBlocking: true },
  { id: '21', text: '21. Tem tido febre persistente (> 10 dias), suores noturnos, perda de peso nos últimos 03 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Sintomas sistêmicos B.', isBlocking: true },
  { id: '22', text: '22. Já teve anemia? Ha quanto tempo? Usou medicação? Teve ou tem doença hemorrágica?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico de anemia ou hemorragia.', isBlocking: true },
  { id: '23', text: '23. Está com algum ferimento no corpo, boca, manchas escuras, ganglios e inguas?', type: 'boolean', expectedAnswer: false, failureMessage: 'Lesões ou linfadenopatia.', isBlocking: true },
  { id: '24', text: '24. Já teve ou tem Hanseniase (lepra), Calazar, Brucelose, Filariose?', type: 'boolean', expectedAnswer: false, failureMessage: 'Doença infecciosa específica.', isBlocking: true },
  { id: '25', text: '25. Já teve ou tem alguma doença do coração? Qual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Cardiopatia.', isBlocking: true },
  { id: '26', text: '26. Já teve ou tem alguma doença do pulmão? (pneumonia, tuberculose, tosse persistente)', type: 'boolean', expectedAnswer: false, failureMessage: 'Pneumopatia ou Tuberculose.', isBlocking: true },
  { id: '27', text: '27. Já teve ou tem alguma doença do rim?', type: 'boolean', expectedAnswer: false, failureMessage: 'Nefropatia.', isBlocking: true },
  { id: '28', text: '28. Já teve ou tem alguma doença do figado?', type: 'boolean', expectedAnswer: false, failureMessage: 'Hepatopatia.', isBlocking: true },
  { id: '29', text: '29. Tem história de úlcera, gastrite?', type: 'boolean', expectedAnswer: false, failureMessage: 'Úlcera ou gastrite.', isBlocking: true },
  { id: '30', text: '30. Tem diarreia persistente? Teve diarreia os últimos 10 dias?', type: 'boolean', expectedAnswer: false, failureMessage: 'Diarreia recente.', isBlocking: true },
  { id: '31', text: '31. Realizou algum procedimento endoscópico nos últimos 06 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Procedimento endoscópico recente.', isBlocking: true },
  { id: '32', text: '32. Tem alguma doença crônica? Faz algum tratamento ou acompanhamento médico?', type: 'boolean', expectedAnswer: false, failureMessage: 'Doença crônica em acompanhamento.', isBlocking: false },
  { id: '33', text: '33. Já teve ou tem câncer, diabetes ou doença da tireoide?', type: 'boolean', expectedAnswer: false, failureMessage: 'Neoplasia, diabetes ou tireoide.', isBlocking: false },
  { id: '34', text: '34. Já teve ou tem alergia, asma, falta de ar bronquite? Medicação nos últimos 15 dias?', type: 'boolean', expectedAnswer: false, failureMessage: 'Alergia ou asma ativa.', isBlocking: false },
  { id: '35', text: '35. Tem pressão alta? Usa medicação? Qual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Hipertensão / Uso de anti-hipertensivo.', isBlocking: false },
  { id: '36', text: '36. Tem tendência e desmaiou pressão baixa?', type: 'boolean', expectedAnswer: false, failureMessage: 'Hipotensão ou síncope.', isBlocking: false },
  { id: '37', text: '37. Já teve convulsão, foco (disritmia). Epilepsia?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico de Epilepsia/Convulsão.', isBlocking: true },
  { id: '38', text: '38. Usa ou usou medicações controladas, anticonvulsivantes? Quando e durante quanto tempo?', type: 'boolean', expectedAnswer: false, failureMessage: 'Uso de medicação controlada.', isBlocking: true },
  { id: '39', text: '39. Esta com alguma inflamação no momento?', type: 'boolean', expectedAnswer: false, failureMessage: 'Processo inflamatório ativo.', isBlocking: true },
  { id: '40', text: '40. Teve febre, gripe nos últimos 07 dias? Rubéola nos últimos 03 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Gripe ou Rubéola recente.', isBlocking: true },
  { id: '41', text: '41. Teve Dengue, Zika ou Chikungunya? Quando? Contato domiciliar? (avaliar deslocamento)', type: 'boolean', expectedAnswer: false, failureMessage: 'Arbovirose recente.', isBlocking: true },
  { id: '42', text: '42. Já teve alguma DST? Qual? Há quanto tempo?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico de DST.', isBlocking: true },
  { id: '43', text: '43. Já teve relação sexual com prostituta? Pagou para fazer sexo? Há quanto tempo?', type: 'boolean', expectedAnswer: false, failureMessage: 'Sexo comercial.', isBlocking: true },
  { id: '44', text: '44. Teve relação sexual com pessoa desconhecida, promiscua, homo ou bissexual? Quando?', type: 'boolean', expectedAnswer: false, failureMessage: 'Relação sexual de risco.', isBlocking: true },
  { id: '45', text: '45. Já teve ou tem relação sexual com pessoa usuária de drogas/tóxicos?', type: 'boolean', expectedAnswer: false, failureMessage: 'Relação com usuário de drogas.', isBlocking: true },
  { id: '46', text: '46. Já teve ou tem relação sexual com pessoas portadoras de hepatite, HIV, HTLV?', type: 'boolean', expectedAnswer: false, failureMessage: 'Relação com portador de infecção viral.', isBlocking: true },
  { id: '47', text: '47. Já teve ou tem relação sexual ou experiência homossexual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Atenção: Avaliar comportamento de risco (Regra técnica de triagem).', isBlocking: false },
  { id: '48', text: '48. Teve algum(a) parceiro(a) sexual novo(a) nos últimos 06 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Parceiro sexual novo recente.', isBlocking: true },
  { id: '49', text: '49. Teve relação com parceiros(as) diferentes nos últimos 12 meses? Quantos?', type: 'boolean', expectedAnswer: false, failureMessage: 'Múltiplos parceiros sexuais.', isBlocking: true },
  { id: '50', text: '50. Teve contato sexual com pessoa que fez transfusão sanguínea ou hemodiálise no último ano?', type: 'boolean', expectedAnswer: false, failureMessage: 'Contato com transfundido/hemodialítico.', isBlocking: true },
  { id: '51', text: '51. Fez alguma cirurgia nos últimos 06 meses? Cirurgia Bariátrica?', type: 'boolean', expectedAnswer: false, failureMessage: 'Cirurgia recente.', isBlocking: true },
  { id: '52', text: '52. Foi preso em instituição carcerária ou policial alguma vez? Quando?', type: 'boolean', expectedAnswer: false, failureMessage: 'Encarceramento.', isBlocking: true },
  { id: '53', text: '53. Já usou algum tipo de droga: maconha, cocaina, crack ou drogas injetáveis?', type: 'boolean', expectedAnswer: false, failureMessage: 'Uso de drogas injetáveis/inalatórias.', isBlocking: true },
  { id: '54', text: '54. Já recebeu transfusão de sangue, hemoderivados, transplante de órgãos ou tecidos?', type: 'boolean', expectedAnswer: false, failureMessage: 'Transfusão ou Transplante prévio.', isBlocking: true },
  { id: '55', text: '55. Realizou algum tratamento dentário nos últimos 15 dias?', type: 'boolean', expectedAnswer: false, failureMessage: 'Procedimento odontológico.', isBlocking: true },
  { id: '56', text: '56. Fez tatuagem ou piercing nos últimos 12 meses? Tem piercing oral ou genital?', type: 'boolean', expectedAnswer: false, failureMessage: 'Tatuagem ou piercing.', isBlocking: true },
  { id: '57', text: '57. Teve acidente perfurocortante (risco biológico) no último ano?', type: 'boolean', expectedAnswer: false, failureMessage: 'Acidente com risco biológico.', isBlocking: true },
  { id: '58', text: '58. Está grávida, amamentando ou teve algum aborto nos últimos 03 meses?', type: 'boolean', expectedAnswer: false, failureMessage: 'Gravidez, amamentação ou aborto.', isBlocking: true },
  { id: '59', text: '59. Está com alguma alteração do ciclo menstrual?', type: 'boolean', expectedAnswer: false, failureMessage: 'Alteração no ciclo menstrual.', isBlocking: false },
  { id: '60', text: '60. Já esteve grávida quanta vezes?', type: 'boolean', expectedAnswer: false, failureMessage: 'Histórico de gestações.', isBlocking: false }
];