"""Add repasse and local_aplicacao to OdontoProcedimento

Revision ID: 3edce609b4e0
Revises: c2d3e4f5a6b7
Create Date: 2026-07-22 22:57:21.102538
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3edce609b4e0'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odonto_procedimentos', sa.Column('valor_repasse', sa.Float(), nullable=True))
    op.add_column('odonto_procedimentos', sa.Column('tipo_repasse', sa.String(), nullable=True))
    op.add_column('odonto_procedimentos', sa.Column('local_aplicacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odonto_procedimentos', 'local_aplicacao')
    op.drop_column('odonto_procedimentos', 'tipo_repasse')
    op.drop_column('odonto_procedimentos', 'valor_repasse')
    # ### end Alembic commands ###
