"""initial schema

Revision ID: 49998e323487
Revises: 
Create Date: 2026-07-08 22:44:35.356237
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49998e323487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=False)
    op.create_table('modulos',
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.String(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('procedimento_id', sa.String(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('data_agendamento', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.String(), nullable=True),
    sa.Column('hora_fim', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('numero_guia', sa.String(), nullable=True),
    sa.Column('valor_cobrado', sa.Float(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_empresa_id'), 'agendamentos', ['empresa_id'], unique=False)
    op.create_table('anamnese_odonto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('respostas', sa.JSON(), nullable=True),
    sa.Column('data_avaliacao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anamnese_odonto_empresa_id'), 'anamnese_odonto', ['empresa_id'], unique=False)
    op.create_table('atendimentos_clinicos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('data_atendimento', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_clinicos_empresa_id'), 'atendimentos_clinicos', ['empresa_id'], unique=False)
    op.create_table('caixa_lancamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_lancamentos_empresa_id'), 'caixa_lancamentos', ['empresa_id'], unique=False)
    op.create_table('caixa_turnos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('recepcionista_id', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('status_auditoria', sa.String(), nullable=True),
    sa.Column('comissao_recepcionista', sa.Float(), nullable=True),
    sa.Column('total_arrecadado', sa.Float(), nullable=True),
    sa.Column('total_retido_clinica', sa.Float(), nullable=True),
    sa.Column('total_repasse_medicos', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_turnos_empresa_id'), 'caixa_turnos', ['empresa_id'], unique=False)
    op.create_table('clinica_dados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chave', sa.String(), nullable=True),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinica_dados_chave'), 'clinica_dados', ['chave'], unique=False)
    op.create_index(op.f('ix_clinica_dados_empresa_id'), 'clinica_dados', ['empresa_id'], unique=False)
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('codigo_ans', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('percentual_repasse', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convenios_empresa_id'), 'convenios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_convenios_id'), 'convenios', ['id'], unique=False)
    op.create_index(op.f('ix_convenios_nome'), 'convenios', ['nome'], unique=False)
    op.create_table('custos_operacionais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('frequencia', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custos_operacionais_empresa_id'), 'custos_operacionais', ['empresa_id'], unique=False)
    op.create_table('documentos_atendimento',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('atendimento_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_atendimento_empresa_id'), 'documentos_atendimento', ['empresa_id'], unique=False)
    op.create_table('especialidades_odonto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_especialidades_odonto_empresa_id'), 'especialidades_odonto', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_especialidades_odonto_nome'), 'especialidades_odonto', ['nome'], unique=False)
    op.create_table('estoque_categorias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_categorias_empresa_id'), 'estoque_categorias', ['empresa_id'], unique=False)
    op.create_table('estoque_fornecedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj_cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_fornecedores_empresa_id'), 'estoque_fornecedores', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_estoque_fornecedores_nome'), 'estoque_fornecedores', ['nome'], unique=False)
    op.create_table('estoque_movimentacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('produto_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('referencia_tipo', sa.String(), nullable=True),
    sa.Column('referencia_id', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_movimentacoes_empresa_id'), 'estoque_movimentacoes', ['empresa_id'], unique=False)
    op.create_table('estoque_pedidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.String(), nullable=True),
    sa.Column('fornecedor_id', sa.String(), nullable=True),
    sa.Column('itens_texto', sa.Text(), nullable=True),
    sa.Column('custo_estimado', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('aprovado_por', sa.String(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_pedidos_empresa_id'), 'estoque_pedidos', ['empresa_id'], unique=False)
    op.create_table('estoque_pedidos_itens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.String(), nullable=True),
    sa.Column('produto_id', sa.String(), nullable=True),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=True),
    sa.Column('quantidade_recebida', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_pedidos_itens_empresa_id'), 'estoque_pedidos_itens', ['empresa_id'], unique=False)
    op.create_table('estoque_produtos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.String(), nullable=True),
    sa.Column('fornecedor_id', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('unidades_por_embalagem', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_produtos_empresa_id'), 'estoque_produtos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_estoque_produtos_nome'), 'estoque_produtos', ['nome'], unique=False)
    op.create_table('estoque_saldo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('produto_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_saldo_empresa_id'), 'estoque_saldo', ['empresa_id'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('usuario_nome', sa.String(), nullable=True),
    sa.Column('acao', sa.String(), nullable=True),
    sa.Column('modulo', sa.String(), nullable=True),
    sa.Column('entidade', sa.String(), nullable=True),
    sa.Column('entidade_id', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_auditoria_empresa_id'), 'eventos_auditoria', ['empresa_id'], unique=False)
    op.create_table('evolucoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('atendimento_id', sa.String(), nullable=True),
    sa.Column('texto_evolucao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolucoes_empresa_id'), 'evolucoes', ['empresa_id'], unique=False)
    op.create_table('financeiro_contas_pagar',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pedido_id', sa.String(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('comprovante_url', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('aprovado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financeiro_contas_pagar_empresa_id'), 'financeiro_contas_pagar', ['empresa_id'], unique=False)
    op.create_table('financeiro_lancamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('procedimento_id', sa.String(), nullable=True),
    sa.Column('mes', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financeiro_lancamentos_empresa_id'), 'financeiro_lancamentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_financeiro_lancamentos_mes'), 'financeiro_lancamentos', ['mes'], unique=False)
    op.create_index(op.f('ix_financeiro_lancamentos_procedimento_id'), 'financeiro_lancamentos', ['procedimento_id'], unique=False)
    op.create_table('laudos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('recepcao_lab_id', sa.String(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laudos_empresa_id'), 'laudos', ['empresa_id'], unique=False)
    op.create_table('modelos_prontuario',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('conteudo', sa.JSON(), nullable=True),
    sa.Column('tipo_acesso', sa.String(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_prontuario_empresa_id'), 'modelos_prontuario', ['empresa_id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publico_alvo', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_empresa_id'), 'notificacoes', ['empresa_id'], unique=False)
    op.create_table('odonto_procedimentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome_intervencao', sa.String(), nullable=True),
    sa.Column('valor_base', sa.Float(), nullable=True),
    sa.Column('especialidade_id', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('materiais', sa.JSON(), nullable=True),
    sa.Column('tipo_visual', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odonto_procedimentos_empresa_id'), 'odonto_procedimentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_odonto_procedimentos_nome_intervencao'), 'odonto_procedimentos', ['nome_intervencao'], unique=False)
    op.create_table('orcamento_itens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('orcamento_id', sa.String(), nullable=True),
    sa.Column('dente_numero', sa.String(), nullable=True),
    sa.Column('faces', sa.String(), nullable=True),
    sa.Column('procedimento_id', sa.String(), nullable=True),
    sa.Column('valor_cobrado', sa.Float(), nullable=True),
    sa.Column('status_item', sa.String(), nullable=True),
    sa.Column('status_visual', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamento_itens_empresa_id'), 'orcamento_itens', ['empresa_id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('status_geral', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_empresa_id'), 'orcamentos', ['empresa_id'], unique=False)
    op.create_table('orcamentos_odonto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('status_geral', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_odonto_empresa_id'), 'orcamentos_odonto', ['empresa_id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('responsavel_nome', sa.String(), nullable=True),
    sa.Column('responsavel_cpf', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('logradouro', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('plano_saude', sa.String(), nullable=True),
    sa.Column('carteirinha_numero', sa.String(), nullable=True),
    sa.Column('carteirinha_validade', sa.Date(), nullable=True),
    sa.Column('alergias', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=False)
    op.create_index(op.f('ix_pacientes_empresa_id'), 'pacientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=False)
    op.create_table('perfis_usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('nome_social', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('is_dono', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('especialidade_medica', sa.String(), nullable=True),
    sa.Column('conselho_tipo', sa.String(), nullable=True),
    sa.Column('conselho_numero', sa.String(), nullable=True),
    sa.Column('conselho_uf', sa.String(), nullable=True),
    sa.Column('conselho', sa.String(), nullable=True),
    sa.Column('numero_conselho', sa.String(), nullable=True),
    sa.Column('uf_conselho', sa.String(), nullable=True),
    sa.Column('rqe_numero', sa.String(), nullable=True),
    sa.Column('rqe_uf', sa.String(), nullable=True),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfis_usuarios_email'), 'perfis_usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_perfis_usuarios_empresa_id'), 'perfis_usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_perfis_usuarios_nome'), 'perfis_usuarios', ['nome'], unique=False)
    op.create_table('procedimento_materiais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('procedimento_id', sa.String(), nullable=True),
    sa.Column('produto_id', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedimento_materiais_empresa_id'), 'procedimento_materiais', ['empresa_id'], unique=False)
    op.create_table('procedimentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('duracao', sa.Integer(), nullable=True),
    sa.Column('cor_hex', sa.String(), nullable=True),
    sa.Column('valor_padrao', sa.Float(), nullable=True),
    sa.Column('valor_repasse', sa.Float(), nullable=True),
    sa.Column('tipo_repasse', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedimentos_empresa_id'), 'procedimentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_procedimentos_nome'), 'procedimentos', ['nome'], unique=False)
    op.create_table('recebimentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.String(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('caixa_turno_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recebimentos_empresa_id'), 'recebimentos', ['empresa_id'], unique=False)
    op.create_table('recebimentos_avulsos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('forma_pagamento', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recebimentos_avulsos_empresa_id'), 'recebimentos_avulsos', ['empresa_id'], unique=False)
    op.create_table('recepcao_lab',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('laboratorio', sa.String(), nullable=True),
    sa.Column('tipo_trabalho', sa.String(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepcao_lab_empresa_id'), 'recepcao_lab', ['empresa_id'], unique=False)
    op.create_table('repasses_profissionais',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.String(), nullable=True),
    sa.Column('periodo_ini', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('valor_faturado', sa.Float(), nullable=True),
    sa.Column('percentual_repasse', sa.Float(), nullable=True),
    sa.Column('valor_repasse', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repasses_profissionais_empresa_id'), 'repasses_profissionais', ['empresa_id'], unique=False)
    op.create_table('repasses_recepcionistas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('recepcionista_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('referencia', sa.String(), nullable=True),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repasses_recepcionistas_empresa_id'), 'repasses_recepcionistas', ['empresa_id'], unique=False)
    op.create_table('salas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('cor_hex', sa.String(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salas_empresa_id'), 'salas', ['empresa_id'], unique=False)
    op.create_table('tabela_laboratorio',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exame', sa.String(), nullable=True),
    sa.Column('laboratorio', sa.String(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('prazo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabela_laboratorio_empresa_id'), 'tabela_laboratorio', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_tabela_laboratorio_exame'), 'tabela_laboratorio', ['exame'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_empresa_id'), 'unidades', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_unidades_id'), 'unidades', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('cid', sa.String(), nullable=True),
    sa.Column('cid_descricao', sa.String(), nullable=True),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_empresa_id'), 'consultas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('usuario_filiais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('is_admin_filial', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['perfis_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'unidade_id', name='uq_usuario_filial')
    )
    op.create_index(op.f('ix_usuario_filiais_empresa_id'), 'usuario_filiais', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_filiais_unidade_id'), 'usuario_filiais', ['unidade_id'], unique=False)
    op.create_index(op.f('ix_usuario_filiais_usuario_id'), 'usuario_filiais', ['usuario_id'], unique=False)
    op.create_table('usuario_permissoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('modulo', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['modulo'], ['modulos.chave'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['perfis_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'unidade_id', 'modulo', name='uq_usuario_perm')
    )
    op.create_index(op.f('ix_usuario_permissoes_empresa_id'), 'usuario_permissoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_permissoes_unidade_id'), 'usuario_permissoes', ['unidade_id'], unique=False)
    op.create_index(op.f('ix_usuario_permissoes_usuario_id'), 'usuario_permissoes', ['usuario_id'], unique=False)
    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('memed_id', sa.String(), nullable=True),
    sa.Column('link_receita', sa.String(), nullable=True),
    sa.Column('resumo_html', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescricoes_empresa_id'), 'prescricoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_prescricoes_id'), 'prescricoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescricoes_id'), table_name='prescricoes')
    op.drop_index(op.f('ix_prescricoes_empresa_id'), table_name='prescricoes')
    op.drop_table('prescricoes')
    op.drop_index(op.f('ix_usuario_permissoes_usuario_id'), table_name='usuario_permissoes')
    op.drop_index(op.f('ix_usuario_permissoes_unidade_id'), table_name='usuario_permissoes')
    op.drop_index(op.f('ix_usuario_permissoes_empresa_id'), table_name='usuario_permissoes')
    op.drop_table('usuario_permissoes')
    op.drop_index(op.f('ix_usuario_filiais_usuario_id'), table_name='usuario_filiais')
    op.drop_index(op.f('ix_usuario_filiais_unidade_id'), table_name='usuario_filiais')
    op.drop_index(op.f('ix_usuario_filiais_empresa_id'), table_name='usuario_filiais')
    op.drop_table('usuario_filiais')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_empresa_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_unidades_id'), table_name='unidades')
    op.drop_index(op.f('ix_unidades_empresa_id'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_tabela_laboratorio_exame'), table_name='tabela_laboratorio')
    op.drop_index(op.f('ix_tabela_laboratorio_empresa_id'), table_name='tabela_laboratorio')
    op.drop_table('tabela_laboratorio')
    op.drop_index(op.f('ix_salas_empresa_id'), table_name='salas')
    op.drop_table('salas')
    op.drop_index(op.f('ix_repasses_recepcionistas_empresa_id'), table_name='repasses_recepcionistas')
    op.drop_table('repasses_recepcionistas')
    op.drop_index(op.f('ix_repasses_profissionais_empresa_id'), table_name='repasses_profissionais')
    op.drop_table('repasses_profissionais')
    op.drop_index(op.f('ix_recepcao_lab_empresa_id'), table_name='recepcao_lab')
    op.drop_table('recepcao_lab')
    op.drop_index(op.f('ix_recebimentos_avulsos_empresa_id'), table_name='recebimentos_avulsos')
    op.drop_table('recebimentos_avulsos')
    op.drop_index(op.f('ix_recebimentos_empresa_id'), table_name='recebimentos')
    op.drop_table('recebimentos')
    op.drop_index(op.f('ix_procedimentos_nome'), table_name='procedimentos')
    op.drop_index(op.f('ix_procedimentos_empresa_id'), table_name='procedimentos')
    op.drop_table('procedimentos')
    op.drop_index(op.f('ix_procedimento_materiais_empresa_id'), table_name='procedimento_materiais')
    op.drop_table('procedimento_materiais')
    op.drop_index(op.f('ix_perfis_usuarios_nome'), table_name='perfis_usuarios')
    op.drop_index(op.f('ix_perfis_usuarios_empresa_id'), table_name='perfis_usuarios')
    op.drop_index(op.f('ix_perfis_usuarios_email'), table_name='perfis_usuarios')
    op.drop_table('perfis_usuarios')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_empresa_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_orcamentos_odonto_empresa_id'), table_name='orcamentos_odonto')
    op.drop_table('orcamentos_odonto')
    op.drop_index(op.f('ix_orcamentos_empresa_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_orcamento_itens_empresa_id'), table_name='orcamento_itens')
    op.drop_table('orcamento_itens')
    op.drop_index(op.f('ix_odonto_procedimentos_nome_intervencao'), table_name='odonto_procedimentos')
    op.drop_index(op.f('ix_odonto_procedimentos_empresa_id'), table_name='odonto_procedimentos')
    op.drop_table('odonto_procedimentos')
    op.drop_index(op.f('ix_notificacoes_empresa_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_modelos_prontuario_empresa_id'), table_name='modelos_prontuario')
    op.drop_table('modelos_prontuario')
    op.drop_index(op.f('ix_laudos_empresa_id'), table_name='laudos')
    op.drop_table('laudos')
    op.drop_index(op.f('ix_financeiro_lancamentos_procedimento_id'), table_name='financeiro_lancamentos')
    op.drop_index(op.f('ix_financeiro_lancamentos_mes'), table_name='financeiro_lancamentos')
    op.drop_index(op.f('ix_financeiro_lancamentos_empresa_id'), table_name='financeiro_lancamentos')
    op.drop_table('financeiro_lancamentos')
    op.drop_index(op.f('ix_financeiro_contas_pagar_empresa_id'), table_name='financeiro_contas_pagar')
    op.drop_table('financeiro_contas_pagar')
    op.drop_index(op.f('ix_evolucoes_empresa_id'), table_name='evolucoes')
    op.drop_table('evolucoes')
    op.drop_index(op.f('ix_eventos_auditoria_empresa_id'), table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index(op.f('ix_estoque_saldo_empresa_id'), table_name='estoque_saldo')
    op.drop_table('estoque_saldo')
    op.drop_index(op.f('ix_estoque_produtos_nome'), table_name='estoque_produtos')
    op.drop_index(op.f('ix_estoque_produtos_empresa_id'), table_name='estoque_produtos')
    op.drop_table('estoque_produtos')
    op.drop_index(op.f('ix_estoque_pedidos_itens_empresa_id'), table_name='estoque_pedidos_itens')
    op.drop_table('estoque_pedidos_itens')
    op.drop_index(op.f('ix_estoque_pedidos_empresa_id'), table_name='estoque_pedidos')
    op.drop_table('estoque_pedidos')
    op.drop_index(op.f('ix_estoque_movimentacoes_empresa_id'), table_name='estoque_movimentacoes')
    op.drop_table('estoque_movimentacoes')
    op.drop_index(op.f('ix_estoque_fornecedores_nome'), table_name='estoque_fornecedores')
    op.drop_index(op.f('ix_estoque_fornecedores_empresa_id'), table_name='estoque_fornecedores')
    op.drop_table('estoque_fornecedores')
    op.drop_index(op.f('ix_estoque_categorias_empresa_id'), table_name='estoque_categorias')
    op.drop_table('estoque_categorias')
    op.drop_index(op.f('ix_especialidades_odonto_nome'), table_name='especialidades_odonto')
    op.drop_index(op.f('ix_especialidades_odonto_empresa_id'), table_name='especialidades_odonto')
    op.drop_table('especialidades_odonto')
    op.drop_index(op.f('ix_documentos_atendimento_empresa_id'), table_name='documentos_atendimento')
    op.drop_table('documentos_atendimento')
    op.drop_index(op.f('ix_custos_operacionais_empresa_id'), table_name='custos_operacionais')
    op.drop_table('custos_operacionais')
    op.drop_index(op.f('ix_convenios_nome'), table_name='convenios')
    op.drop_index(op.f('ix_convenios_id'), table_name='convenios')
    op.drop_index(op.f('ix_convenios_empresa_id'), table_name='convenios')
    op.drop_table('convenios')
    op.drop_index(op.f('ix_clinica_dados_empresa_id'), table_name='clinica_dados')
    op.drop_index(op.f('ix_clinica_dados_chave'), table_name='clinica_dados')
    op.drop_table('clinica_dados')
    op.drop_index(op.f('ix_caixa_turnos_empresa_id'), table_name='caixa_turnos')
    op.drop_table('caixa_turnos')
    op.drop_index(op.f('ix_caixa_lancamentos_empresa_id'), table_name='caixa_lancamentos')
    op.drop_table('caixa_lancamentos')
    op.drop_index(op.f('ix_atendimentos_clinicos_empresa_id'), table_name='atendimentos_clinicos')
    op.drop_table('atendimentos_clinicos')
    op.drop_index(op.f('ix_anamnese_odonto_empresa_id'), table_name='anamnese_odonto')
    op.drop_table('anamnese_odonto')
    op.drop_index(op.f('ix_agendamentos_empresa_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
