"""Add profissional_id to CaixaLancamento

Revision ID: 9e15ff1c1bca
Revises: 3edce609b4e0
Create Date: 2026-08-06 11:47:06.354434
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e15ff1c1bca'
down_revision: Union[str, None] = '3edce609b4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caixa_lancamentos', sa.Column('profissional_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caixa_lancamentos', 'profissional_id')
    # ### end Alembic commands ###
